pipeline {
    agent{
        node{
            label 'docker-agent-python'
        }
    }
    triggers{
        pollSCM 'H/5 * * * *'
    }
    stages {
        stage('Build') {
            steps {
                echo "building..."
                sh '''
                cd app
                pip install -r requirements.txt
                '''
            }
        }

        stage('Testing') {
            steps {
                echo "Testing..."
                sh '''
                cd app
                python3 app.py
                python3 hello.py --name=Imran
                '''
            }
        }
        stage('Deliver'){
            steps{
                echo "deliver..."
                sh '''
                echo "doing delivery stuff"
                '''
            }
        }
    }
}

